-- Signal — Phase 1 Foundation · 0005 FEED + INTELLIGENCE
CREATE TABLE IF NOT EXISTS public.story_clusters (
  id               text PRIMARY KEY,
  canonical_title  text,
  canonical_url    text,
  content_category text,
  source_count     integer NOT NULL DEFAULT 1,
  confidence_score integer NOT NULL DEFAULT 0,
  best_score       integer NOT NULL DEFAULT 0,
  source_urls      jsonb NOT NULL DEFAULT '[]'::jsonb,
  last_seen_at     timestamptz NOT NULL DEFAULT now(),
  created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.feed_items (
  id                       text PRIMARY KEY,
  title                    text NOT NULL,
  summary                  text NOT NULL,
  why_it_matters           text,
  what_happened            text,
  opportunity              text,
  who_for                  text,
  url                      text NOT NULL,
  tag                      text CHECK (tag IN ('tool','news','prompt','use-case')),
  source                   text,
  source_label             text,
  source_urls              jsonb NOT NULL DEFAULT '[]'::jsonb,
  category                 text,
  content_category         text NOT NULL DEFAULT 'Must Know',
  score                    integer NOT NULL DEFAULT 0,
  usefulness               integer NOT NULL DEFAULT 0,
  vibe_friendly            boolean NOT NULL DEFAULT false,
  humanized                boolean NOT NULL DEFAULT false,
  engagement               integer NOT NULL DEFAULT 0,
  underrated               boolean NOT NULL DEFAULT false,
  growth                   text,
  impact                   text NOT NULL DEFAULT 'useful'
                             CHECK (impact IN ('critical','major','useful')),
  novelty_score            integer NOT NULL DEFAULT 0,
  business_impact_score    integer NOT NULL DEFAULT 0,
  builder_value_score      integer NOT NULL DEFAULT 0,
  adoption_potential_score integer NOT NULL DEFAULT 0,
  market_impact_score      integer NOT NULL DEFAULT 0,
  confidence_score         integer NOT NULL DEFAULT 0,
  opportunity_score        integer NOT NULL DEFAULT 0,
  corroboration_score      integer NOT NULL DEFAULT 0,
  source_count             integer NOT NULL DEFAULT 1,
  leverage_score           integer NOT NULL DEFAULT 0,
  trend_score              integer NOT NULL DEFAULT 0,
  momentum_score           integer NOT NULL DEFAULT 0,
  action_label             text,
  action                   text,
  risk                     text,
  who_benefits             text,
  who_should_ignore        text,
  expected_impact          text,
  time_horizon             text,
  trend_entities           text[] NOT NULL DEFAULT '{}'::text[],
  ranking_reason           text,
  published_at             timestamptz NOT NULL,
  fetched_at               timestamptz NOT NULL DEFAULT now(),
  created_at               timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.story_intelligence (
  feed_item_id    text PRIMARY KEY REFERENCES public.feed_items (id) ON DELETE CASCADE,
  intelligence    jsonb NOT NULL,
  significance    integer NOT NULL DEFAULT 0,
  trend_name      text,
  trend_direction text,
  model           text,
  degraded        boolean NOT NULL DEFAULT false,
  created_at      timestamptz NOT NULL DEFAULT now()
);
